# Basic Zephyr kernel support
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_ASYNC_API=y

# Console/logging can interfere with a UART used for the lab link.
# EDIT/ENABLE your preferred debug console separately if needed.
CONFIG_PRINTK=y

# Synchronization
CONFIG_KERNEL_MUTEX=y

# Do not use malloc for the UART protocol.
CONFIG_HEAP_MEM_POOL_SIZE=0
